export const srcBase = './src'
export const distBase = './dist'
export const srcPath = {
    'scss': srcBase + '/scss/**/*.scss',
    'img': srcBase + '/img/**/*',
    'js': srcBase + '/js/**/*.js',
    'json': srcBase + '/**/*.json',
    'xml': srcBase + '/xml/*',
    'ejs': srcBase + '/**/*.ejs',
    'herolist': [
        srcBase + '/_inc/_order_by_range.ejs', 
        srcBase + '/_inc/_list.ejs', 
        srcBase + '/_inc/_head.ejs', 
        srcBase + '/index.ejs'
    ],
    'hero': [
        srcBase + '/hero/hero.ejs', 
        srcBase + '/_inc/_contents.ejs', 
        srcBase + '/_inc/_head.ejs'
    ],
    '_ejs': '!' + srcBase + '/_inc/**/*.ejs',
};

export const distPath = {
    'css': distBase + '/css',
    'img': distBase + '/img',
    'js': distBase + '/js',
    'hero': distBase + '/hero',
};

export const def = {
    "単体攻撃": "a",
    "複数攻撃": "b",
    "六人攻撃": "c",
    "全体攻撃": "d",
    "バフのみ": "e",
    "HP回復": "f",
    "自身HP回復": "g",
    "自身MP回復": "h",
    "自身物理攻撃UP": "i",
    "自身魔法攻撃UP": "j",
    "自身物理クリティカルUP": "k",
    "自身魔法クリティカルUP": "l",
    "自身行動速度UP": "m",
    "自身属性攻撃UP": "n",
    "自身ダメージUP": "o",
    "自身条件付ダメージUP": "p",
    "自身回数付ダメージUP": "q",
    "自身回数付物理ダメージUP": "r",
    "自身回数付魔法ダメージUP": "s",
    "W攻撃": "t",
    "自身スキルダメージUP": "u",
    "自身奥義ダメージUP": "v",
    "自身デバフ耐性": "w",
    "MP回復": "x",
    "物理攻撃UP": "y",
    "魔法攻撃UP": "z",
    "物理クリティカルUP": "aa",
    "魔法クリティカルUP": "ab",
    "行動速度UP": "ac",
    "スキルダメージUP": "ad",
    "奥義ダメージUP": "ae",
    "属性攻撃UP": "af",
    "ダメージUP": "ag",
    "デバフ耐性": "ah",
    "物理防御DOWN": "ai",
    "魔法防御DOWN": "aj",
    "行動速度DOWN": "ak",
    "被ダメージUP": "al",
    "回数付ダメージUP": "am",
    "回数付物理ダメージUP": "an",
    "回数付魔法ダメージUP": "ao",
    "デバフ解除": "ap",
    "挑発": "aq",
    "毒": "ar",
    "火傷": "as",
    "凍結": "at",
    "石化": "au",
    "睡眠": "av",
    "沈黙": "aw",
    "眩暈": "ax",
    "麻痺": "ay",
    "混乱": "az",
    "魅了": "ba",
    "呪い": "bb",
    "盲目": "bc",
    "解消": "bd",
    "挑発耐性": "be",
    "毒耐性": "bf",
    "火傷耐性": "bg",
    "凍結耐性": "bh",
    "石化耐性": "bi",
    "睡眠耐性": "bj",
    "沈黙耐性": "bk",
    "眩暈耐性": "bl",
    "麻痺耐性": "bm",
    "混乱耐性": "bn",
    "魅了耐性": "bo",
    "呪い耐性": "bp",
    "盲目耐性": "bq",
    "解消耐性": "br",
    "出血": "bs",
    "出血耐性": "bt",
    "恐怖": "bu",
    "恐怖耐性": "bv"
};